### ISSUE TITLE
bug: weak constraint of ipv4 and incorrect code logic in hostname_from_ip

### ISSUE THREAD

**Issue by Smityz** [XiaoMi/rdsn#405]
https://github.com/XiaoMi/rdsn/blob/07f2e659a9330c16421cc6ea6eb34282bf48d7eb/src/core/core/utils.cpp#L116
`addr.from_string_ipv4` is too weak to limit the ipv4 address, it only judges by the format of addresses, and don't care about if its value valid. So this function can't limit ip address like `123.456.789.123`

https://github.com/XiaoMi/rdsn/blob/07f2e659a9330c16421cc6ea6eb34282bf48d7eb/src/core/core/utils.cpp#L130
https://github.com/XiaoMi/rdsn/blob/ca49482a57c8470a9f44fc904284e64fdc523a49/src/core/tests/hostname_test.cpp#L40
This unit test should not be done like this,`address.type() != HOST_TYPE_IPV4` can't tell if its value valid, because `address.type` has been assigned before it was passed in.

**Comment by neverchanje** [comment]
What condition does our `from_string_ipv4` make a problem?
