### ISSUE TITLE
partition split

### ISSUE THREAD

**Issue by shengofsun** [XiaoMi/rdsn#69]
### 最主要的考虑点

split的动作，在primary和secondary之间最好在同样的decree点之后发生。这样，对于某条写请求，可以明确的界定是由parent分片负责还是child分片负责。

如果没有规定一个固定的decree点，某个请求在不同副本间可能会由不同的partition负责，会有一些胡乱。

### 一种思路：2pc split

如果把split动作做成一个mutation, 走一致性协议。那么究竟在哪个点进行split,副本间就可以达到统一的共识了。事实上一致性协议就是干这件事情的，它本来就是用来保证主从之间的“复制状态机”的，如果把split也作为一种主从间的状态变化的话，这种做法是非常自然的。

#### mutation重放的问题

1. 对于一条已经commit的split message 我们只要强制要求这条message必须flush/durable就行。这样replica在重启的时候是不会重放这条mutation的。

2. 如果replica group发生了configuration变化，mutation也不会发生重放。这是我们的一致性协议保证的：

   * 一个没有commit的mutation, 只会把ballot变一下然后重新2pc, 而把原来的message给覆盖掉。
   * 一个已经commit了的message, 不会因为replica group的变化而重放。

3. 退一步讲：果给每一条split的mutation指定好partition version，也就是说“本split希望partition count是从几变到几”，那么即使一个mutation要执行两次，貌似也不会有影响？因为我们可以在apply这条mutation的时候判断这个split还有没有必要做。

   而且由于一致性协议的保证，这条mutation即便进行了重放，在三个副本之间的行为也是一模一样的。

#### primary如何apply "split mutation"

1. 首先像所有的write mutation一样，先prepare，等所有的副本都prepare之后，primary就可以commit了。

2. commit时候，replica要：

   * 初始化一个新的空replica
   * clone一份storage_engine出来; 如果是rocksdb, 需要打hardlink
   * clone一份private log出来
   * clone replica相关的所有数据结构：replica config, primary context, secondary context，cold_backup_context, replica_config
   * 对于context里面涉及到的一些task需要做一些更为细致的讨论。对于常规任务类型的task，需要重新启动一个新的task: 比如各种timer, 以及冷备的rpc，热备的任务等等。其他的一些任务则需要把task置空

   replica的commit过程就有点像进程的fork：复制内存镜像，对内核的数据结构做修改；我们需要做的是复制数据，对各种控制行为做修改。

   可能这里会觉得commit的过程过于繁琐。但不管怎样的split方案，一个replica一分为二后，里面所对应的各种控制行为该怎么变化都是需要细致的考虑的。

   这也是我喜欢2pc的原因，精确的相同decree点上的split, 能让我们更好的对“split前后parent、child”的行为做思考和控制。

3. primary在commit之后，split结束。

#### secondary如何applit "split mutation"

secondary的split过程和primary基本相同。但由于是2pc, primary在split结束后，secondary还没有split。

只有等新的一条mutation后发出后，才会推动secondary的commit。这条mutattion可能是一条普通的写，也可能是一条group check。但这条mutation一定得是parent发出的一条mutation; 如果是child, 它会发现其他副本还不存在这个partition而被拒绝掉，这里我们需要特殊处理下：

* 在prepare阶段，如果因为partition version太低而发生的partition不存在，primary应该delay重试，而不是踢掉secondary。

#### split时候的一些其他问题

1. 需要修改下clientlet, 让child partition标志为还没有被任何线程access过，因为parent和child可能会被分派到不同的线程池

#### split的时候发生replica group变化

因为replica的所有状态变化都是线性的，所以这里可以明确的讨论：

* 变化发生在split之前，这个变化和split没有关系
* 变化发生在split之后。
  * 首先：split已经commit, 所以重放是不会发生的。
  * 其次，如果一个secondary升级成primary。那么就需要考虑这条mutation在这个secondary这里有没有提交。提交了就没啥影响；如果没有提交，就会因为提交而secondary也发生split。

#### split之前的learner和split之后的primary

设想一种场景：learner的decree在split之前，而primary已经是split之后了；在这种情况下，如果简单的learn会导致learner面对"split的mutation"无所适从。

这里我们可以简单处理：如果partition的version不一致，强制要求"learn from scratch"。

另一种方式是跳过split的控制命令。

#### 和meta的交互

meta在下发split消息的时候，可以通过config sync，也可以通过单独的命令。

当primary在完成split的时候，需要通知meta说split已经完成，这时meta会更新remote-storage, 把parent和child的partition configuration都更新一下，在此之前，child的partition configuration为空。

config-sync的时候，如果因为partition version不一致而导致replica-server上缺乏一些partition，可以暂时先忽略掉。因为split的mutation是走过两阶段提交的，这条mutation一定会发生，而不会丢失。

#### 和client的交互

和之前的设计应该可以维持一致。

#### 优化

1. replica clone的时候阻塞write线程池的问题：应该可以拿到后台线程做的。
2. split的时候不停写：只要保证split后面的东西暂时不commit就可以了。
   * 可以放宽读写一致性的要求：在三副本prepare完了之后就立马回复client端成功(目前实现一下可能要改接口)

### 另一种思路：控制命令式split(TBD)

大概想了下：split如果没有同步点，在prepare的时候会比较混乱。如果也走这种“通知secondary-等待回复”的流程，其实和走2pc也差不多。

另外需要考虑下，primary split完成、通知meta修改partition config，primary挂了之后的一些情况

**Comment by neverchanje** [comment]
[这里](https://www.icloud.com/pages/0vzczX6EHhoGkH76OP9DW4sUg#split_%E8%AE%BE%E8%AE%A1%E6%96%87%E6%A1%A3) 是 partition split 的设计文档, 其中包括了对设计的讨论, 还有对设计思路的讲解. 其中我对 **"2PC split"** 和 **"控制命令式 split"** 都做了设计.

**Comment by shengofsun** [comment]
@neverchanje 你能把icloud的文档搬到github上来吗？我们统一在这里修改吧。
另外我看了你昨天发的pdf，感觉和我们写的东西其实也不冲突。我相当于给你补充了细节。
比较重要的点是”最好能做到有一个同步点",不管是用哪种方式。

**Comment by neverchanje** [comment]
# split 设计文档

## 功能介绍

使指定表的 partition count 成 2 倍增加。为保证服务稳定，原有 partition id 不变，但每个 partition 会一分为二。每次 split 操作只能扩容一倍，例如从 {1, 2, 3, ... 8} 扩容至 {1, 2, 3, ... 16}。(关于成 2 倍扩容, 参见 FAQ-Q1)。 

由于成 2 倍扩容, 数据将从 partition p 迁移到 partition (p+old_partition_count). 我们将前者称为 **parent**, 后者称为 **child**. 为了使得 split 操作尽可能轻量, 我们使用硬链接来避免数据的拷贝. parent 和 child 共享同一硬盘, 避免数据拷贝. (关于 rocksdb sst 的硬链接, 参见 FAQ-Q2)

整体 split 过程可以大致分为以下几个阶段：
- client 将 split 请求发到 meta
- meta 将 split 任务同步到各个 primaries
- primary 指挥各自 partition group 进行分裂，分裂出新的 partition 后需要向 meta 进行注册，新的 
- partition 注册后即可服务，不必等待其他 partition 激活完成
- 当所有 partitions 都成功分裂并注册，meta 将结束 split

## 接口

```
split <app_name> <new_partition_count>
```

**参数检查**：
- 如果已有 split 正在进行，返回 ERR_BUSY。
- 如果 new_partition_count != old_partition_count*2，返回 ERR_INVALID_PARAMETERS。
- 如果当前表不可用，返回 ERR_APP_NOT_EXIST。

## Meta Server 设计

- **client 将 split 请求发到 meta**：每次 split，meta 会进入扩容状态，在该状态下服务照常，但拒绝新的 split 直到当前 split 完成。随后 meta server 立刻将 new partition count 记录至 zk，记录成功才对 client 返回 ERR_OK。此时新增 partition 的 ballot 为 -1，只有在该 partition 成功一分为二后，ballot 才会被设为可用值。客户端可通过 ballot 是否设置得知当前 split 进度。

- **meta 将 split 任务同步到各个 primaries**：这里我们使用 config sync 来同步信息。primary 根据 partition count 是否更新来判断是否进行分裂。即使发生 replica failover，或者 partition group 不完整，meta server 也会将 new partition count 同步给 primary，从而促使其分裂，primary 自行判断是否继续进行 split。

- **new primary 激活**：分裂完成后，parent primary 会主动通知 meta server，使 child 能够被激活。激活时，meta server 将更新 child 的 ballot = parent’s ballot + 1，并相应更新 child 的 partition configuration。

## Replica Server 设计

- primary 通过 config sync 收到 partition count 的更新，认定是一个 split 指令。如果当前已有 split 正在进行，则忽略。partition group 的数量不足 3 个时或者当前正在进行 learn，primary 将忽略这次 split 请求，等待下次 config sync。如果一切正常, 则开始 split.

- primary 首先会向 secondaries 进行 2PC 写下 RPC_PARTITION_SPLIT_2PC 日志. 在日志提交后, 各个节点进行 split 操作.

- 执行 split. 具体过程：
1. primary 异步告知 meta server 进行子节点的注册. 我们认为 split 2pc 日志一旦提交, child 即已存在.
primary 拒绝写请求, 使 partition 处于停服状态. 随后异步进行 split, 避免影响 replication 线程池.
replica_stub 创建 replica
2. 利用 rocksdb checkpoint (需要 flush memtable) 将 sst 文件硬链接至 tmp 目录下, 链接完成后 rename 至 child replica 下. 随后重启 rocksdb. replica_stub 重启时遇到 tmp 目录则忽略, 遇到正确的 replica 目录则读取.
3. 更新 last_flushed_decree 后恢复写请求, 从此拒绝处理所有属于 child 的请求, 我们通过 last_flushed_decree 在故障恢复时判断是否需要重新进行 split.

## FAQ
**Q1: 为什么 partition count 只允许 2 倍扩容而不是随意值扩容?**
A: 考虑 partition count 从 4 扩容至 7, 原本 hash=8 的数据将从 partition 4 迁移至 partition 1, hash=12 的数据将从 partition 4 迁移至 partition 5. 可见 partition 4 的数据将会被迁移至多处.
经过简单的数学推断, 可以知道只有扩容 2 倍才能使迁移的目的地最少.

**Q2: 既然 parent 和 child 通过硬链接共享 sst 文件, 它们的写修改是否对对方可见?**
A:  不可见.

**Q：既然是成倍扩容，那用户为什么必须提供 new_partition_count 参数？**
A：为了避免 client 操作重试，由于操作不幂等，多次重试的 split 可能将表非预期地扩容多倍

**Q：可否取消正在进行的 split？**
A：暂时未计划支持取消。操作 split 时需要格外小心。

**Q：可否不使用 config_sync 传达 split 命令?**
A: 我们同样可以在 meta server 使用 send_proposal 操作传达命令. 但这样的工作量与 config sync 相差不大.

**Q：如果 replica (机器 A) 在 split 过程中故障恢复迁移至 机器 B, 此时 A 上有 child 目录, 但** last_flushed_decree 未更新. 它将会在机器 B 上重新 split 出 child replica. 如何处理一个 replica 有两个对应 child 的情况?
A: 不需要额外处理, rdsn 保证最多只有 3 个 replica 可用.

**Q：如果机器 A 故障重启, parent 的 last_flushed_decree 尚未更新, 但是 child 已经成功被 split, 此时是否还需要重新 split?**
A: 需要, 我们会移除这个 child. 避免读取到很久以前创建的 child 目录。

## 不通过 2PC 进行 split 的方案讨论

- primary 拒绝写, 进入停服状态。
- primary 通过 group_split_rpc 通知 secondaries 进行 split。在 split 完成前，group_split_rpc 会作为心跳检测周期询问 secondaries。三个节点都完成后, split 结束. 随后在 meta server 上注册 child。
- split 过程即进行 rocksdb checkpoint，中间文件暂放至 tmp 目录下，checkpoint 结束才彻底 rename 至 child replica 目录。我们通过 rename 标志一个节点的 split 是否完成。
- primary 服务恢复。

假设一个 secondary 故障，partition group 内的 3 节点都需要等待它恢复。secondary 恢复时需要 primary 的 group_split_rpc 心跳以得知自己需要进行 split。

假设是 primary 发生故障，新上任的 primary 可以通过 config sync 得知 split 操作尚未完成。从而发起新的 split。

这种方案相较于 2PC 的优点在于：
- 将 split 与 2PC 剥离，使 split 成为独立模块，并且不需要写日志

而缺点在于：
- 容错性低，一个节点故障会导致整个 partition 长时间不可用。
- 三节点都结束 split 并且通知 meta server 后才可恢复服务，停服时间较长。

**Comment by hycdong** [comment]
总结一下5月30号对partition split功能讨论的结果。
## 方案讨论
### 讨论的有以下三种方案：
1. 远南的思路 - child异步learn，partition都完成split后向meta register child partition
    拒绝写时间：从primary向meta发出register child partition请求  -> 收到meta register ERR_OK
2. 两阶段提交，且将split请求添加到mutation log中，只要primary完成split将向meta register所有child partition
    停写时间为：split 请求发出 -> primary register all child partition
3. 两阶段提交，请求不基于mutation log实现，所有partition都完成split后向meta register child partition
    停写时间为：split请求发出 -> primary register all child partition

### 三种方案各有利弊：
- 方案1：
    - 优点：工作量较小，拒绝客户端写耗时最短
    - 缺点：异步learn较为复杂，增加逻辑理解难度
- 方案2：
    - 优点：逻辑理解较为简单，与方案三相比停写时间稍短
    - 缺点：需要对多个模块进行修改，corner case较多
- 方案3：
    - 优点：逻辑理解较为简单
    - 缺点：停写时间较长

### 讨论结论
为了保证正确性，尽快实现功能，现在暂时将采用**方案1**，但仍会对方案二的corner case进行思考，若停写时间能够在可接受范围，并且能够梳理清逻辑且实现不复杂，可以改为方案2，对该方案的讨论和需要理顺的corner case如下

## 2pc + mutation方案讨论
### 方案概述
通过mutation log和两阶段提交实现split功能大致分为以下4个步骤：
1. primary prepare
2. secondary prepare
3. 收到所有secondary prepare完成后primary commit
4. secondary异步commit

其中，第3步完成后及认为split完成，而commit阶段需要大致完成如下步骤：
1. 根据parent创建一个新的replica实例
2. 给当前rocksdb打checkpoint
3. 复制private log文件，mutation等结构
4. （仅primary）向meta发送register all child replica

### 方案所需特殊处理和边界思考
以下思考为对讨论的总结，更详细的可参见@伟杰的第一个comment
- 需要对在primary注册child partition到secondary commit之间的写请求进行特殊处理
- 出错处理思考：
  - 如何处理split时的learner
  - 如何处理对split mutation的replay问题

**Comment by hycdong** [comment]
Partition split is developed and tested, I will split my code into several pull requests and merge them into master. Here are the normal partition split process:
1.  shell -> meta to start partition split
2. meta
    - update partition count */= 2 on zk and meta server
3. replica
    - parent notice partition count changed in on_config_sync
    - parent init child replica instance
    - parent prepare its own state (prepare list, mutation, private log)
    - child async learn
    - child notify parent primary finish split
    - child group update partition count
    - group child catch, check sync_point and stop read and write
    - primary -> meta to register child partition
4. meta
    - meta register child on zk
    - meta register child on meta server local
    - send ack to primary
5. replica
    - parent group update partition count
    - parent active child
    - primary recover read and write
