### ISSUE TITLE
ut: Failed to mutation_log_test when I build test by debug on tag v2.2.3

### ISSUE THREAD

**Issue by GehaFearless** [XiaoMi/rdsn#930]
when I build test by debug on tag v2.2.3, failed message:
"mutation_log.cpp:464:mutation_log(): assertion expression: _private_gpid == r->get_gpid()"
"mutation_log.cpp:464:mutation_log(): (29696.7367936) VS (1.1)"
But it passed when I try build test by release, what should I do?

**Comment by GreenDaySky** [comment]
execute command: 
`./run.sh test -c --skip_thirdparty -t debug`
complete log：
1.standard output:
`[ RUN      ] mutation_log_test.replay_multiple_files_20000_1mb
[       OK ] mutation_log_test.replay_multiple_files_20000_1mb (902 ms)
[ RUN      ] mutation_log_test.replay_multiple_files_50000_1mb
[       OK ] mutation_log_test.replay_multiple_files_50000_1mb (2184 ms)
[ RUN      ] mutation_log_test.replay_start_decree
[       OK ] mutation_log_test.replay_start_decree (16 ms)
[ RUN      ] mutation_log_test.reset_from
F2021-10-08 14:32:50.254 (1633674770254779415 12873) replica.default0.0000323300010001: mutation_log.cpp:464:mutation_log(): assertion expression: _private_gpid == r->get_gpid()
F2021-10-08 14:32:50.254 (1633674770254795405 12873) replica.default0.0000323300010001: mutation_log.cpp:464:mutation_log(): (29696.7367936) VS (1.1)
ERROR: run dsn.replica.test failed, return_code = 134`
2.standard error:
`./run.sh: ./clear.sh: /: bad interpreter: Permission denied
./run.sh: line 9: 12851 Aborted                 (core dumped) GTEST_OUTPUT="xml:${output_xml}" ./dsn.replica.test`
